# ricu_preprocessing_extra.py
import logging
logging.basicConfig(
    level=logging.INFO,  # Set logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'  # Customize output format
)
logger = logging.getLogger(__name__)

ALL_FEATURES=("icds","ts_eos","ts_po2","static_adm","ts_epi_dur","ts_pt","static_age","ts_epi_rate","ts_ptt","static_bmi","ts_esr","ts_qsofa","static_height","ts_fgn","ts_rass","static_los_hosp","ts_fio2","ts_rbc","static_los_icu","ts_gcs","ts_rdw","static_sex","ts_glu","ts_resp","static_weight","ts_hba1c","ts_safi","ts_abx","ts_hct","ts_samp","ts_adh_rate","ts_hgb","ts_sbp","ts_alb","ts_hr","ts_sep3","ts_alp","ts_inr_pt","ts_sirs","ts_alt","ts_ins","ts_sofa_cardio","ts_ast","ts_k","ts_sofa_cns","ts_avpu","ts_lact","ts_sofa_coag","ts_basos","ts_lymph","ts_sofa","ts_be","ts_map","ts_sofa_liver","ts_bicar","ts_mchc","ts_sofa_renal","ts_bili","ts_mch","ts_sofa_resp","ts_bili_dir","ts_mcv","ts_supp_o2","ts_bnd","ts_methb","ts_susp_inf","ts_bun","ts_mews","ts_tco2","ts_ca","ts_mgcs","ts_temp","ts_cai","ts_mg","ts_tgcs","ts_ck","ts_na","ts_tnt","ts_ckmb","ts_neut","ts_tri","ts_cl","ts_news","ts_urine24","ts_crea","ts_norepi60","ts_urine","ts_crp","ts_norepi_dur","ts_vaso_ind","ts_dbp","ts_norepi_equiv","ts_vent_end","ts_death","ts_norepi_rate","ts_vent_start","ts_dobu60","ts_o2sat","ts_vgcs","ts_dobu_dur","ts_pafi","ts_wbc","ts_dobu_rate","ts_pco2","ws_dex","ts_dopa60","ts_ph","ws_ett_gcs","ts_dopa_dur","ts_phn_rate","ws_vent_ind","ts_dopa_rate","ts_phos","ts_egcs","ts_plt",)
COMMON_FEATURES = ('static_age','static_bmi','static_height','static_sex','static_weight','ts_abx','ts_alb','ts_alt','ts_ast','ts_bicar','ts_bili','ts_bili_dir','ts_bun','ts_ca','ts_cai','ts_ck','ts_ckmb','ts_cl','ts_crea','ts_dbp','ts_dobu60','ts_dobu_dur','ts_dobu_rate','ts_epi60','ts_epi_dur','ts_epi_rate','ts_fgn','ts_fio2','ts_glu','ts_k','ts_lact','ts_lymph','ts_map','ts_mchc','ts_mch','ts_mcv','ts_mg','ts_na','ts_neut',)
PRIMARY_KEY_MAP = {
    "eicu": "patientunitstayid",
    "mimic": "icustay_id",
    "miiv": "stay_id",
    "eicu_demo": "patientunitstayid",
    "mimic_demo": "icustay_id",
    "hirid": "patientid",
    "sic": "CaseID"
}

LABEL_KEY_MAP = {
    "eicu": "icd9code",
    "mimic": "icd9_code",
    "miiv": "icd_code",
    "eicu_demo": "icd9code",
    "mimic_demo": "icd9_code",
    "sic": "ICD9Main"
}

TIME_VARS_MAP_DATASET_LIST_KEYS = {
    "eicu": ["infusionoffset", "labresultoffset", "nursingchartoffset", "observationoffset", "respcarestatusoffset", "intakeoutputoffset", "culturetakenoffset", "drugstartoffset"],
    "eicu_demo": ["infusionoffset", "labresultoffset", "nursingchartoffset", "observationoffset", "respcarestatusoffset", "intakeoutputoffset", "culturetakenoffset", "drugstartoffset"],
    "mimic": ['charttime', 'chartdate', 'index_var', 'startdate', 'starttime'],
    "mimic_demo": ['charttime', 'chartdate', 'index_var', 'startdate', 'starttime'],
}



static_vars = ['sex']
ts_idx_vars = []
ts_ct_vars = []
ts_cd_vars = []
ws_vars = []


eicu_feature_type_map = {
    "abx": bool,
    "adh_rate": float,
    "alb": float,
    "alp": int,
    "alt": int,
    "ast": int,
    "avpu": str,
    "basos": int,
    "be": int,
    "bicar": int,
    "bili": float,
    "bili_dir": float,
    "bnd": int,
    "bun": int,
    "ca": float,
    "cai": float,
    "ck": int,
    "ckmb": float,
    "cl": int,
    "crea": float,
    "crp": int,
    "dbp": int,
    "death": bool,
    "dobu60": float,
    "dobu_dur": int,
    "dobu_rate": float,
    "dopa60": float,
    "dopa_dur": int,
    "dopa_rate": int,
    "egcs": int,
    "eos": int,
    "epi60": float,
    "epi_dur": int,
    "epi_rate": float,
    "fgn": int,
    "fio2": int,
    "gcs": int,
    "glu": int,
    "hbco": float,
    "hct": float,
    "hgb": float,
    "hr": int,
    "inr_pt": float,
    "ins": float,
    "k": float,
    "lact": float,
    "lymph": int,
    "map": float,
    "mch": float,
    "mchc": float,
    "mcv": float,
    "methb": float,
    "mews": int,
    "mg": int,
    "mgcs": int,
    "na": int,
    "neut": int,
    "news": int,
    "norepi60": float,
    "norepi_dur": int,
    "norepi_equiv": float,
    "norepi_rate": float,
    "o2sat": int,
    "pafi": float,
    "pco2": int,
    "ph": float,
    "phn_rate": int,
    "phos": float,
    "plt": int,
    "po2": int,
    "pt": float,
    "ptt": int,
    "qsofa": int,
    "rass": int,
    "rbc": float,
    "rdw": float,
    "resp": int,
    "safi": float,
    "samp": bool,
    "sbp": int,
    "sep3": bool,
    "sirs": int,
    "sofa": int,
    "sofa_cardio": int,
    "sofa_cns": int,
    "sofa_coag": int,
    "sofa_liver": int,
    "sofa_renal": int,
    "sofa_resp": int,
    "supp_o2": bool,
    "susp_inf": bool,
    "tco2": int,
    "temp": float,
    "tgcs": int,
    "tnt": float,
    "tri": float,
    "urine": int,
    "urine24": int,
    "vaso_ind": bool,
    "vent_end": bool,
    "vent_start": bool,
    "vgcs": int,
    "wbc": float,
    "dex": int,
    "ett_gcs": bool,
    "vent_ind": bool
}


mimic_feature_type_map = {
    "icustay_id": int,
    "icd9_code": str,
    "adm": str,
    "age": float,
    "bmi": float,
    "height": float,
    "los_hosp": float,
    "los_icu": float,
    "sex": str,
    "weight": float,
    "startdate": int,
    "abx": bool,
    "adh_rate": float,
    "alb": float,
    "alp": int,
    "alt": int,
    "ast": int,
    "avpu": str,
    "basos": int,
    "be": int,
    "bicar": int,
    "bili": float,
    "bili_dir": float,
    "bnd": int,
    "bun": int,
    "ca": float,
    "cai": float,
    "ck": int,
    "ckmb": float,
    "cl": int,
    "crea": float,
    "crp": int,
    "dbp": int,
    "death": bool,
    "dobu60": float,
    "dobu_dur": int,
    "dobu_rate": float,
    "dopa60": float,
    "dopa_dur": int,
    "dopa_rate": int,
    "egcs": int,
    "eos": int,
    "epi_dur": int,
    "epi_rate": float,
    "fgn": int,
    "fio2": int,
    "gcs": int,
    "glu": int,
    "hbco": float,
    "hct": float,
    "hgb": float,
    "hr": int,
    "inr_pt": float,
    "ins": float,
    "k": float,
    "lact": float,
    "lymph": int,
    "map": float,
    "mch": float,
    "mchc": float,
    "mcv": float,
    "methb": float,
    "mews": int,
    "mg": int,
    "mgcs": int,
    "na": int,
    "neut": int,
    "news": int,
    "norepi60": float,
    "norepi_dur": int,
    "norepi_equiv": float,
    "norepi_rate": float,
    "o2sat": int,
    "pafi": float,
    "pco2": int,
    "ph": float,
    "phn_rate": int,
    "phos": float,
    "plt": int,
    "po2": int,
    "pt": float,
    "ptt": int,
    "qsofa": int,
    "rass": int,
    "rbc": float,
    "rdw": float,
    "resp": int,
    "safi": float,
    "samp": bool,
    "sbp": int,
    "sep3": bool,
    "sirs": int,
    "sofa": int,
    "sofa_cardio": int,
    "sofa_cns": int,
    "sofa_coag": int,
    "sofa_liver": int,
    "sofa_renal": int,
    "sofa_resp": int,
    "supp_o2": bool,
    "susp_inf": bool,
    "tco2": int,
    "temp": float,
    "tgcs": int,
    "tnt": float,
    "tri": float,
    "urine": int,
    "urine24": int,
    "vaso_ind": bool,
    "vent_end": bool,
    "vent_start": bool,
    "vgcs": int,
    "wbc": float,
    "dex": int,
    "ett_gcs": bool,
    "vent_ind": bool
}


fnames = {
    "miiv": ("miiv_ts_avpu.csv","miiv_ts_dbp.csv","miiv_ts_fgn.csv","miiv_ts_mch.csv","miiv_ts_pco2.csv","miiv_ts_sbp.csv","miiv_ts_urine24.csv","miiv_static_adm.csv","miiv_ts_basos.csv","miiv_ts_death.csv","miiv_ts_fio2.csv","miiv_ts_mcv.csv","miiv_ts_ph.csv","miiv_ts_sep3.csv","miiv_ts_urine.csv","miiv_static_age.csv","miiv_ts_be.csv","miiv_ts_dobu60.csv","miiv_ts_gcs.csv","miiv_ts_methb.csv","miiv_ts_phn_rate.csv","miiv_ts_sirs.csv","miiv_ts_vaso_ind.csv","miiv_static_bmi.csv","miiv_ts_bicar.csv","miiv_ts_dobu_dur.csv","miiv_ts_glu.csv","miiv_ts_mews.csv","miiv_ts_phos.csv","miiv_ts_sofa_cardio.csv","miiv_ts_vgcs.csv","miiv_static_height.csv","miiv_ts_bili.csv","miiv_ts_dobu_rate.csv","miiv_ts_hba1c.csv","miiv_ts_mgcs.csv","miiv_ts_plt.csv","miiv_ts_sofa_cns.csv","miiv_ts_wbc.csv","miiv_static_los_hosp.csv","miiv_ts_bili_dir.csv","miiv_ts_dopa60.csv","miiv_ts_hct.csv","miiv_ts_mg.csv","miiv_ts_po2.csv","miiv_ts_sofa_coag.csv","miiv_ws_dex.csv","miiv_static_los_icu.csv","miiv_ts_bnd.csv","miiv_ts_dopa_dur.csv","miiv_ts_hgb.csv","miiv_ts_na.csv","miiv_ts_pt.csv","miiv_ts_sofa.csv","miiv_ws_ett_gcs.csv","miiv_static_sex.csv","miiv_ts_bun.csv","miiv_ts_dopa_rate.csv","miiv_ts_hr.csv","miiv_ts_neut.csv","miiv_ts_ptt.csv","miiv_ts_sofa_liver.csv","miiv_ws_mech_vent.csv","miiv_static_weight.csv","miiv_ts_ca.csv","miiv_ts_egcs.csv","miiv_ts_inr_pt.csv","miiv_ts_news.csv","miiv_ts_qsofa.csv","miiv_ts_sofa_renal.csv","miiv_ws_vent_ind.csv","miiv_ts_abx.csv","miiv_ts_cai.csv","miiv_ts_eos.csv","miiv_ts_ins.csv","miiv_ts_norepi60.csv","miiv_ts_rass.csv","miiv_ts_sofa_resp.csv","miiv_ts_adh_rate.csv","miiv_ts_ck.csv","miiv_ts_epi60.csv","miiv_ts_k.csv","miiv_ts_norepi_dur.csv","miiv_ts_rbc.csv","miiv_ts_supp_o2.csv","miiv_ts_alb.csv","miiv_ts_ckmb.csv","miiv_ts_epi_dur.csv","miiv_ts_lact.csv","miiv_ts_norepi_equiv.csv","miiv_ts_rdw.csv","miiv_ts_susp_inf.csv","miiv_ts_alp.csv","miiv_ts_cl.csv","miiv_ts_epi_rate.csv","miiv_ts_lymph.csv","miiv_ts_norepi_rate.csv","miiv_ts_resp.csv","miiv_ts_tco2.csv","miiv_ts_alt.csv","miiv_ts_crea.csv","miiv_ts_esr.csv","miiv_ts_map.csv","miiv_ts_o2sat.csv","miiv_ts_safi.csv","miiv_ts_temp.csv","miiv_ts_ast.csv","miiv_ts_crp.csv","miiv_ts_etco2.csv","miiv_ts_mchc.csv","miiv_ts_pafi.csv","miiv_ts_samp.csv","miiv_ts_tnt.csv",),
    "mimic_demo" : ("mimic_demo_ts_mchc.csv","mimic_demo_static_adm.csv","mimic_demo_ts_mcv.csv","mimic_demo_static_age.csv","mimic_demo_ts_methb.csv","mimic_demo_static_bmi.csv","mimic_demo_ts_mews.csv","mimic_demo_static_height.csv","mimic_demo_ts_mg.csv","mimic_demo_static_los_hosp.csv","mimic_demo_ts_mgcs.csv","mimic_demo_static_los_icu.csv","mimic_demo_ts_na.csv","mimic_demo_static_sex.csv","mimic_demo_ts_neut.csv","mimic_demo_static_weight.csv","mimic_demo_ts_news.csv","mimic_demo_ts_abx.csv","mimic_demo_ts_norepi60.csv","mimic_demo_ts_adh_rate.csv","mimic_demo_ts_norepi_dur.csv","mimic_demo_ts_alb.csv","mimic_demo_ts_norepi_equiv.csv","mimic_demo_ts_alp.csv","mimic_demo_ts_norepi_rate.csv","mimic_demo_ts_alt.csv","mimic_demo_ts_o2sat.csv","mimic_demo_ts_ast.csv","mimic_demo_ts_pafi.csv","mimic_demo_ts_avpu.csv","mimic_demo_ts_pco2.csv","mimic_demo_ts_basos.csv","mimic_demo_ts_ph.csv","mimic_demo_ts_be.csv","mimic_demo_ts_phn_rate.csv","mimic_demo_ts_bicar.csv","mimic_demo_ts_phos.csv","mimic_demo_ts_bili.csv","mimic_demo_ts_plt.csv","mimic_demo_ts_bili_dir.csv","mimic_demo_ts_po2.csv","mimic_demo_ts_bnd.csv","mimic_demo_ts_pt.csv","mimic_demo_ts_bun.csv","mimic_demo_ts_ptt.csv","mimic_demo_ts_ca.csv","mimic_demo_ts_qsofa.csv","mimic_demo_ts_cai.csv","mimic_demo_ts_rass.csv","mimic_demo_ts_ck.csv","mimic_demo_ts_rbc.csv","mimic_demo_ts_ckmb.csv","mimic_demo_ts_rdw.csv","mimic_demo_ts_cl.csv","mimic_demo_ts_resp.csv","mimic_demo_ts_crea.csv","mimic_demo_ts_safi.csv","mimic_demo_ts_crp.csv","mimic_demo_ts_samp.csv","mimic_demo_ts_dbp.csv","mimic_demo_ts_sbp.csv","mimic_demo_ts_death.csv","mimic_demo_ts_sep3.csv","mimic_demo_ts_dobu60.csv","mimic_demo_ts_sirs.csv","mimic_demo_ts_dobu_dur.csv","mimic_demo_ts_sofa.csv","mimic_demo_ts_dobu_rate.csv","mimic_demo_ts_sofa_cardio.csv","mimic_demo_ts_dopa60.csv","mimic_demo_ts_sofa_cns.csv","mimic_demo_ts_dopa_dur.csv","mimic_demo_ts_sofa_coag.csv","mimic_demo_ts_dopa_rate.csv","mimic_demo_ts_sofa_liver.csv","mimic_demo_ts_egcs.csv","mimic_demo_ts_sofa_renal.csv","mimic_demo_ts_eos.csv","mimic_demo_ts_sofa_resp.csv","mimic_demo_ts_epi_dur.csv","mimic_demo_ts_supp_o2.csv","mimic_demo_ts_epi_rate.csv","mimic_demo_ts_susp_inf.csv","mimic_demo_ts_esr.csv","mimic_demo_ts_tco2.csv","mimic_demo_ts_fgn.csv","mimic_demo_ts_temp.csv","mimic_demo_ts_fio2.csv","mimic_demo_ts_tgcs.csv","mimic_demo_ts_gcs.csv","mimic_demo_ts_tnt.csv","mimic_demo_ts_glu.csv","mimic_demo_ts_tri.csv","mimic_demo_ts_hba1c.csv","mimic_demo_ts_urine.csv","mimic_demo_ts_hct.csv","mimic_demo_ts_urine24.csv","mimic_demo_ts_hgb.csv","mimic_demo_ts_vaso_ind.csv","mimic_demo_ts_hr.csv","mimic_demo_ts_vent_end.csv","mimic_demo_ts_inr_pt.csv","mimic_demo_ts_vent_start.csv","mimic_demo_ts_ins.csv","mimic_demo_ts_vgcs.csv","mimic_demo_ts_k.csv","mimic_demo_ts_wbc.csv","mimic_demo_ts_lact.csv","mimic_demo_ws_dex.csv","mimic_demo_ts_lymph.csv","mimic_demo_ws_ett_gcs.csv","mimic_demo_ts_map.csv","mimic_demo_ws_vent_ind.csv","mimic_demo_ts_mch.csv",),
    "eicu_demo" : ("eicu_demo_ts_mch.csv","eicu_demo_ts_mchc.csv","eicu_demo_static_adm.csv","eicu_demo_ts_mcv.csv","eicu_demo_static_age.csv","eicu_demo_ts_methb.csv","eicu_demo_static_bmi.csv","eicu_demo_ts_mews.csv","eicu_demo_static_height.csv","eicu_demo_ts_mg.csv","eicu_demo_static_los_hosp.csv","eicu_demo_ts_mgcs.csv","eicu_demo_static_los_icu.csv","eicu_demo_ts_na.csv","eicu_demo_static_sex.csv","eicu_demo_ts_neut.csv","eicu_demo_static_weight.csv","eicu_demo_ts_news.csv","eicu_demo_ts_abx.csv","eicu_demo_ts_norepi60.csv","eicu_demo_ts_adh_rate.csv","eicu_demo_ts_norepi_dur.csv","eicu_demo_ts_alb.csv","eicu_demo_ts_norepi_equiv.csv","eicu_demo_ts_alp.csv","eicu_demo_ts_norepi_rate.csv","eicu_demo_ts_alt.csv","eicu_demo_ts_o2sat.csv","eicu_demo_ts_ast.csv","eicu_demo_ts_pafi.csv","eicu_demo_ts_avpu.csv","eicu_demo_ts_pco2.csv","eicu_demo_ts_basos.csv","eicu_demo_ts_ph.csv","eicu_demo_ts_be.csv","eicu_demo_ts_phn_rate.csv","eicu_demo_ts_bicar.csv","eicu_demo_ts_phos.csv","eicu_demo_ts_bili.csv","eicu_demo_ts_plt.csv","eicu_demo_ts_bili_dir.csv","eicu_demo_ts_po2.csv","eicu_demo_ts_bnd.csv","eicu_demo_ts_pt.csv","eicu_demo_ts_bun.csv","eicu_demo_ts_ptt.csv","eicu_demo_ts_ca.csv","eicu_demo_ts_qsofa.csv","eicu_demo_ts_cai.csv","eicu_demo_ts_rass.csv","eicu_demo_ts_ck.csv","eicu_demo_ts_rbc.csv","eicu_demo_ts_ckmb.csv","eicu_demo_ts_rdw.csv","eicu_demo_ts_cl.csv","eicu_demo_ts_resp.csv","eicu_demo_ts_crea.csv","eicu_demo_ts_safi.csv","eicu_demo_ts_crp.csv","eicu_demo_ts_samp.csv","eicu_demo_ts_dbp.csv","eicu_demo_ts_sbp.csv","eicu_demo_ts_death.csv","eicu_demo_ts_sep3.csv","eicu_demo_ts_dobu60.csv","eicu_demo_ts_sirs.csv","eicu_demo_ts_dobu_dur.csv","eicu_demo_ts_sofa.csv","eicu_demo_ts_dobu_rate.csv","eicu_demo_ts_sofa_cardio.csv","eicu_demo_ts_dopa60.csv","eicu_demo_ts_sofa_cns.csv","eicu_demo_ts_dopa_dur.csv","eicu_demo_ts_sofa_coag.csv","eicu_demo_ts_dopa_rate.csv","eicu_demo_ts_sofa_liver.csv","eicu_demo_ts_egcs.csv","eicu_demo_ts_sofa_renal.csv","eicu_demo_ts_eos.csv","eicu_demo_ts_sofa_resp.csv","eicu_demo_ts_epi60.csv","eicu_demo_ts_supp_o2.csv","eicu_demo_ts_epi_dur.csv","eicu_demo_ts_susp_inf.csv","eicu_demo_ts_epi_rate.csv","eicu_demo_ts_tco2.csv","eicu_demo_ts_fgn.csv","eicu_demo_ts_temp.csv","eicu_demo_ts_fio2.csv","eicu_demo_ts_tgcs.csv","eicu_demo_ts_gcs.csv","eicu_demo_ts_tnt.csv","eicu_demo_ts_glu.csv","eicu_demo_ts_tri.csv","eicu_demo_ts_hbco.csv","eicu_demo_ts_urine.csv","eicu_demo_ts_hct.csv","eicu_demo_ts_urine24.csv","eicu_demo_ts_hgb.csv","eicu_demo_ts_vaso_ind.csv","eicu_demo_ts_hr.csv","eicu_demo_ts_vent_end.csv","eicu_demo_ts_inr_pt.csv","eicu_demo_ts_vent_start.csv","eicu_demo_ts_ins.csv","eicu_demo_ts_vgcs.csv","eicu_demo_ts_k.csv","eicu_demo_ts_wbc.csv","eicu_demo_ts_lact.csv","eicu_demo_ws_dex.csv","eicu_demo_ts_lymph.csv","eicu_demo_ws_ett_gcs.csv","eicu_demo_ts_map.csv","eicu_demo_ws_vent_ind.csv"),
    "hirid": ("hirid_static_age.csv","hirid_ts_epi_dur.csv","hirid_ts_ph.csv","hirid_static_bmi.csv","hirid_ts_epi_rate.csv","hirid_ts_phos.csv","hirid_static_height.csv","hirid_ts_esr.csv","hirid_ts_plt.csv","hirid_static_los_icu.csv","hirid_ts_etco2.csv","hirid_ts_po2.csv","hirid_static_sex.csv","hirid_ts_fgn.csv","hirid_ts_ptt.csv","hirid_static_weight.csv","hirid_ts_fio2.csv","hirid_ts_qsofa.csv","hirid_ts_abx.csv","hirid_ts_gcs.csv","hirid_ts_rass.csv","hirid_ts_adh_rate.csv","hirid_ts_glu.csv","hirid_ts_resp.csv","hirid_ts_alb.csv","hirid_ts_hbco.csv","hirid_ts_safi.csv","hirid_ts_alp.csv","hirid_ts_hgb.csv","hirid_ts_sbp.csv","hirid_ts_alt.csv","hirid_ts_hr.csv","hirid_ts_sep3.csv","hirid_ts_ast.csv","hirid_ts_inr_pt.csv","hirid_ts_sirs.csv","hirid_ts_avpu.csv","hirid_ts_ins.csv","hirid_ts_sofa_cardio.csv","hirid_ts_be.csv","hirid_ts_k.csv","hirid_ts_sofa_cns.csv","hirid_ts_bicar.csv","hirid_ts_lact.csv","hirid_ts_sofa_coag.csv","hirid_ts_bili.csv","hirid_ts_lymph.csv","hirid_ts_sofa.csv","hirid_ts_bili_dir.csv","hirid_ts_map.csv","hirid_ts_sofa_liver.csv","hirid_ts_bnd.csv","hirid_ts_mchc.csv","hirid_ts_sofa_renal.csv")
}